# Generated by Django 5.1.7 on 2025-03-20 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('route_plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Route Plan ID')),
                ('trip_date', models.DateField(help_text='Date on which this trip is scheduled')),
                ('start_time', models.TimeField(help_text='Planned departure time for this trip')),
                ('end_time', models.TimeField(help_text='Estimated arrival time for this trip')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', help_text='Current status of the trip', max_length=20)),
                ('to_school', models.BooleanField(default=True, help_text='True for trips to school, False for trips from school')),
                ('route_order', models.JSONField(blank=True, help_text='Ordered list of stops as generated by the Mapbox API', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, help_text='Driver assigned to this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driver')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-trip_date', 'start_time'],
                'indexes': [models.Index(fields=['trip_date'], name='routeplan_t_trip_da_208204_idx'), models.Index(fields=['status'], name='routeplan_t_status_994c99_idx'), models.Index(fields=['to_school'], name='routeplan_t_to_scho_032d60_idx')],
            },
        ),
    ]
