# Generated by Django 5.1.7 on 2025-03-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeplan', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='student_list',
            field=models.ManyToManyField(blank=True, help_text='Students assigned to this trip', related_name='trip_assignments', to='students.student'),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_distance',
            field=models.FloatField(blank=True, help_text='Total distance of the route in kilometers', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route_order',
            field=models.JSONField(blank=True, help_text='Ordered list of stops with coordinates as generated by the Mapbox API', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the trip', max_length=20),
        ),
    ]
