# Generated by Django 5.1.7 on 2025-03-23 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('routeplan', '0002_trip_student_list_trip_total_distance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('trip_date', 'to_school', 'driver')},
        ),
    ]
