# Generated by Django 5.1.7 on 2025-03-20 06:51

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('licence_no', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bus_no', models.CharField(max_length=20)),
                ('current_location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Updated via WebSocket when driver is on a trip', null=True, srid=4326)),
                ('location_updated_at', models.DateTimeField(blank=True, help_text='Timestamp of the last location update', null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('offline', 'Offline'), ('on_leave', 'On Leave')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['email'], name='drivers_dri_email_7a875d_idx'), models.Index(fields=['status'], name='drivers_dri_status_d7a5f5_idx'), models.Index(fields=['bus_no'], name='drivers_dri_bus_no_2d0172_idx')],
            },
        ),
    ]
