# Generated by Django 5.1.7 on 2025-03-20 07:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routeplan', '0002_trip_student_list_trip_total_distance_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Attendance ID')),
                ('date', models.DateField(help_text='Date of attendance record')),
                ('presence', models.BooleanField(default=False, help_text='Whether the student was present on the trip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, help_text='User who marked this attendance record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records_marked', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Student whose attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
                ('trip', models.ForeignKey(help_text='Trip for which attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='routeplan.trip')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'student__name'],
                'indexes': [models.Index(fields=['date'], name='attendance__date_61f2e1_idx'), models.Index(fields=['presence'], name='attendance__presenc_7693dc_idx')],
                'unique_together': {('student', 'trip', 'date')},
            },
        ),
    ]
