name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Azure VM via SSH (skip known_hosts check)
      env:
        AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
        AZURE_VM_USERNAME: ${{ secrets.AZURE_VM_USERNAME }}
        AZURE_VM_SSH_KEY: ${{ secrets.AZURE_VM_SSH_KEY }}
      run: |
        # Write the PEM key to a file
        echo "${{ secrets.AZURE_VM_SSH_KEY }}" > azure_vm_key.pem
        chmod 600 azure_vm_key.pem
        
        # SSH into VM, skip host key check like AWS EC2
        ssh -o StrictHostKeyChecking=no -i azure_vm_key.pem ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          set -e  # Exit on error
          
          cd edurider_v2
          git pull origin main
          
          sudo docker compose down
          sudo docker compose up -d --build
          
          # Run migration after containers up
          sudo docker compose exec web python3 manage.py migrate
        EOF
